from qhat.qre.qre_types import GeneralConfiguration, UnitaryConfiguration, value

from openfermion import InteractionOperator, jordan_wigner

from pyLIQTR.BlockEncodings.DoubleFactorized import DoubleFactorized
from pyLIQTR.BlockEncodings.LinearT import Fermionic_LinearT
from pyLIQTR.BlockEncodings.PauliStringLCU import PauliStringLCU
from pyLIQTR.ProblemInstances.ChemicalHamiltonian import ChemicalHamiltonian

import math

# -------------------------------------------------------------------------------------------------

def encode_linear_t(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian):

    config_general.log_verbose("Encoding with fermionic linear-T block encoding from pyLIQTR.")

    raise NotImplementedError()

    # TODO: Needs to be ElectronicStructure instead of ChemicalHamiltonian.  Unfortunately,
    #       ElectronicStructure is hard-coded to work with data files generated by PEST instead of
    #       a Hamiltonian object constructed with pySCF.
    problem_instance = ChemicalHamiltonian(mol_ham=hamiltonian, mol_name="molecular hamiltonian")
    # TODO: Do we want to exercise any of the other options to Fermionic_LinearT?
    return Fermionic_LinearT(
            ProblemInstance=problem_instance,
            energy_error=config_unitary.energy_error
            )

# -------------------------------------------------------------------------------------------------

def encode_pauli_lcu(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian):

    config_general.log_verbose(
            "Encoding with Pauli linear-combination-of-unitaries block encoding from pyLIQTR.")

    # TODO: If every encoding method wraps the hamiltonian in the ChemicalHamiltonian class, then I
    #       should move that wrapping step to the part of the code that generates the hamiltonian.
    #       Then I can do things like have the hamiltonian part of the code return a simplified
    #       test object.  But note that Fermionic_LinearT requires an ElectronicStruture instead of
    #       a ChemicalHamiltonian (see details in encode_linear_t for current problems there).  Can
    #       the ElectronicStructure be wrapped in a ChemicalHamiltonian?  Can methods other than
    #       Linear T use an ElectronicStructure?
    problem_instance = ChemicalHamiltonian(mol_ham=hamiltonian, mol_name="molecular hamiltonian")
    # TODO: Do we want to exercise any of the other options to PauliStringLCU?
    return PauliStringLCU(
            ProblemInstance=problem_instance,
            # TODO: Setting `prepare_type='AS'` might give the alias sampling Obenland mentioned?
            prepare_type='AS',
            # TODO: What to do with energy_error?
            )

# -------------------------------------------------------------------------------------------------

def encode_double_factorization(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian) -> DoubleFactorized:

    config_general.log_verbose("Encoding with double-factorized block encoding from pyLIQTR.")

    # TODO: We need to process the Hamiltonian into a ChemicalHamiltonian.  Under what conditions
    #       can that happen?  Purely-fermionic only?
    problem_instance = ChemicalHamiltonian(
            mol_ham=hamiltonian.get_core_operator(),
            mol_name="molecular hamiltonian")
    # TODO: Do we want to exercise any of the other options to DoubleFactorized?
    return DoubleFactorized(
            ProblemInstance=problem_instance,
            energy_error=config_unitary.energy_error
            )

# -------------------------------------------------------------------------------------------------

def encode_ramped_trotter(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian,
        tevol_hbar):
        #tevol_hbar) -> RampedTrotterizedUnitary:

    # Get the implementation choice from config
    trotter_impl = config_unitary.trotter_implementation

    # Validate the implementation choice
    if trotter_impl not in ('original', 'flattened'):
        raise ValueError(
            f"Invalid trotter_implementation '{trotter_impl}'. "
            f"Must be 'original' or 'flattened'."
        )

    impl_label = f"{trotter_impl} QHAT"
    config_general.log_verbose(f"Encoding with ramped-trotterization method from `common` ({impl_label}).")

    timestep = value(config_unitary.timestep, tevol_hbar)
    assert timestep >= 0.0
    config_general.log(f"-- timestep = {timestep}")
    config_general.t_hbar = timestep

    # Compute the number of Trotter steps based on the Trotter error from arXiv:1912.08854v3
    # Using fast implementation for better performance (100-150x more samples per second)
    from trotter_coefficients_fast import trotter_error_estimator_fast

    # Read error coefficient computation mode from config (with backward-compatible defaults)
    error_coeff_mode = getattr(config_unitary, 'error_coeff_mode', 'monte_carlo')
    error_coeff_auto_exact = getattr(config_unitary, 'error_coeff_auto_exact', False)
    error_coeff_time_limit = getattr(config_unitary, 'error_coeff_time_limit', 60)

    # Validate user configuration
    if error_coeff_mode not in ['monte_carlo', 'exact']:
        config_general.log(f"WARNING: Invalid error_coeff_mode='{error_coeff_mode}', using 'monte_carlo'")
        error_coeff_mode = 'monte_carlo'

    config_general.log(f"-- Error coefficient computation mode: {error_coeff_mode}")
    if error_coeff_mode == 'monte_carlo' and error_coeff_auto_exact:
        config_general.log(f"-- Auto-switch to exact coefficient computation: enabled")
    config_general.log(f"-- Error coefficient time limit: {error_coeff_time_limit}s")

    # Compute error coefficients with user-specified mode
    c1, c2 = trotter_error_estimator_fast(
        hamiltonian.get_grouped_terms(),
        error_coeff_time_limit,
        config_general,
        mode=error_coeff_mode,
        auto_exact=error_coeff_auto_exact
    )
    config_general.log(f"-- Trotter error coefficients: C1 = {c1}, C2 = {c2}")
    assert config_unitary.energy_error is not None
    config_general.log(f"-- allowable energy error = {config_unitary.energy_error} Hartrees")
    config_general.log(f"-- effective energy range = {2 * math.pi / timestep} Hartrees")
    eps_trotter = config_unitary.energy_error * timestep / (2 * math.pi)
    config_general.log(f"-- allowable fractional Trotter error = {eps_trotter}")
    # use config_unitary.energy_error here instead of eps_trotter, because these equations are
    # derived in terms of the absolute energy error rather than the fractional energy error
    s1 = timestep * config_unitary.error_scale * c1 / config_unitary.energy_error
    s2 = timestep * math.sqrt(config_unitary.error_scale * c2 / config_unitary.energy_error)
    config_general.log(f"-- Trotter step count: s1 = {s1}, s2 = {s2}")

    r1 = 1
    r2 = 2
    r4 = 10
    method = "second order"
    Nsteps0 = s2
    if r1 * s1 < r2 * s2:
        method = "first order"
        Nsteps0 = s1
    # TODO: Add fourth-order (possibly only computed if second order is better than first order)
    Nsteps = max(1, math.ceil(Nsteps0))
    config_general.log(f"-- using {method} Trotter formula with {Nsteps} steps ({Nsteps0})")

    # Import the appropriate implementation
    if trotter_impl == 'flattened':
        from common.trotter_flattened import build_ramped_trotterized_unitary
        # Pass combine_terms parameter only for flattened implementation
        return build_ramped_trotterized_unitary(
                hamiltonian.get_all_pauli_strings(return_as='strings').items(),
                method,
                timestep,
                Nsteps,
                combine_terms=config_unitary.trotter_combine_terms)
    else:  # 'original'
        from common.trotter_original import build_ramped_trotterized_unitary
        # Original implementation doesn't support combine_terms parameter
        return build_ramped_trotterized_unitary(
                hamiltonian.get_all_pauli_strings(return_as='strings').items(),
                method,
                timestep,
                Nsteps)

# -------------------------------------------------------------------------------------------------

def encode_as_unitary(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian,
        tevol_hbar):

    config_general.log("Beginning to encode the Hamiltonian as a unitary.")

    if config_unitary.method.lower() in ("double factorization", "double-factorization"):
        return encode_double_factorization(config_general, config_unitary, hamiltonian)
    elif config_unitary.method.lower() in ("pauli lcu", "pauli-lcu", "paulilcu",):
        return encode_pauli_lcu(config_general, config_unitary, hamiltonian)
    elif config_unitary.method.lower() in ("linear t", "linear-t", "lineart",):
        return encode_linear_t(config_general, config_unitary, hamiltonian)
    elif config_unitary.method.lower() in ("first quantization",):
        # TODO: This will be important for Marian's team.  Something is available in pyLIQTR, but
        #       I've not yet looked to see how it works.
        #       -- I'm not sure if it's correct to break first quantization out as a separate
        #          encoding method.  I now suspect that it will probably be part of defining the
        #          Hamiltonian, and then any Hamiltonian will be eligible for encoding to
        #          unitaries.  But I've not confirmed this.
        raise NotImplementedError()
    elif config_unitary.method.lower() in ("ramped trotter"):
        return encode_ramped_trotter(config_general, config_unitary, hamiltonian, tevol_hbar)
    else:
        raise ValueError(f"Invalid unitary encoding method \"{config_unitary.method}\".")
