from common.trotter import build_ramped_trotterized_unitary

from qre_types import GeneralConfiguration, UnitaryConfiguration, value

from openfermion import InteractionOperator, jordan_wigner

from pyLIQTR.BlockEncodings.DoubleFactorized import DoubleFactorized
from pyLIQTR.BlockEncodings.LinearT import Fermionic_LinearT
from pyLIQTR.BlockEncodings.PauliStringLCU import PauliStringLCU
from pyLIQTR.ProblemInstances.ChemicalHamiltonian import ChemicalHamiltonian

import math

# -------------------------------------------------------------------------------------------------

def encode_linear_t(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian):

    config_general.log_verbose("Encoding with fermionic linear-T block encoding from pyLIQTR.")

    raise NotImplementedError()

    # TODO: Needs to be ElectronicStructure instead of ChemicalHamiltonian.  Unfortunately,
    #       ElectronicStructure is hard-coded to work with data files generated by PEST instead of
    #       a Hamiltonian object constructed with pySCF.
    problem_instance = ChemicalHamiltonian(mol_ham=hamiltonian, mol_name="molecular hamiltonian")
    # TODO: Do we want to exercise any of the other options to Fermionic_LinearT?
    return Fermionic_LinearT(
            ProblemInstance=problem_instance,
            energy_error=config_unitary.energy_error
            )

# -------------------------------------------------------------------------------------------------

def encode_pauli_lcu(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian):

    config_general.log_verbose(
            "Encoding with Pauli linear-combination-of-unitaries block encoding from pyLIQTR.")

    # TODO: If every encoding method wraps the hamiltonian in the ChemicalHamiltonian class, then I
    #       should move that wrapping step to the part of the code that generates the hamiltonian.
    #       Then I can do things like have the hamiltonian part of the code return a simplified
    #       test object.  But note that Fermionic_LinearT requires an ElectronicStruture instead of
    #       a ChemicalHamiltonian (see details in encode_linear_t for current problems there).  Can
    #       the ElectronicStructure be wrapped in a ChemicalHamiltonian?  Can methods other than
    #       Linear T use an ElectronicStructure?
    problem_instance = ChemicalHamiltonian(mol_ham=hamiltonian, mol_name="molecular hamiltonian")
    # TODO: Do we want to exercise any of the other options to PauliStringLCU?
    return PauliStringLCU(
            ProblemInstance=problem_instance,
            # TODO: Setting `prepare_type='AS'` might give the alias sampling Obenland mentioned?
            prepare_type='AS',
            # TODO: What to do with energy_error?
            )

# -------------------------------------------------------------------------------------------------

def encode_double_factorization(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian) -> DoubleFactorized:

    config_general.log_verbose("Encoding with double-factorized block encoding from pyLIQTR.")

    # TODO: We need to process the Hamiltonian into a ChemicalHamiltonian.  Under what conditions
    #       can that happen?  Purely-fermionic only?
    problem_instance = ChemicalHamiltonian(
            mol_ham=hamiltonian.get_core_operator(),
            mol_name="molecular hamiltonian")
    # TODO: Do we want to exercise any of the other options to DoubleFactorized?
    return DoubleFactorized(
            ProblemInstance=problem_instance,
            energy_error=config_unitary.energy_error
            )

# -------------------------------------------------------------------------------------------------

def encode_ramped_trotter(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian,
        tevol_hbar):
        #tevol_hbar) -> RampedTrotterizedUnitary:

    config_general.log_verbose("Encoding with ramped-trotterization method from `common`.")

    timestep = value(config_unitary.timestep, tevol_hbar)
    assert timestep >= 0.0
    config_general.log(f"-- timestep = {timestep}")
    config_general.t_hbar = timestep

    # Compute the number of Trotter steps based on the Trotter error from arXiv:1912.08854v3
    from jkg_utils import trotter_error_estimator
    c1, c2 = trotter_error_estimator(hamiltonian.get_grouped_terms(), 60) # TODO: Is 60s the right amount of time?
    config_general.log(f"-- Trotter error coefficients: C1 = {c1}, C2 = {c2}")
    assert config_unitary.energy_error is not None
    config_general.log(f"-- allowable energy error = {config_unitary.energy_error} Hartrees")
    config_general.log(f"-- effective energy range = {2 * math.pi / timestep} Hartrees")
    eps_trotter = config_unitary.energy_error * timestep / (2 * math.pi)
    config_general.log(f"-- allowable fractional Trotter error = {eps_trotter}")
    s1 = timestep * config_unitary.error_scale * c1 / eps_trotter
    s2 = timestep * math.sqrt(config_unitary.error_scale * c2 / eps_trotter)
    config_general.log(f"-- Trotter step count: s1 = {s1}, s2 = {s2}")

    r1 = 1
    r2 = 2
    r4 = 10
    method = "second order"
    Nsteps0 = s2
    if r1 * s1 < r2 * s2:
        method = "first order"
        Nsteps0 = s1
    # TODO: Add fourth-order (possibly only computed if second order is better than first order)
    Nsteps = max(1, math.ceil(Nsteps0))
    config_general.log(f"-- using {method} Trotter formula with {Nsteps} steps ({Nsteps0})")

    return build_ramped_trotterized_unitary(
            hamiltonian.get_all_pauli_strings(return_as='strings').items(),
            method,
            timestep,
            Nsteps)

# -------------------------------------------------------------------------------------------------

def encode_as_unitary(
        config_general: GeneralConfiguration,
        config_unitary: UnitaryConfiguration,
        hamiltonian,
        tevol_hbar):

    config_general.log("Beginning to encode the Hamiltonian as a unitary.")

    if config_unitary.method.lower() in ("double factorization", "double-factorization"):
        return encode_double_factorization(config_general, config_unitary, hamiltonian)
    elif config_unitary.method.lower() in ("pauli lcu", "pauli-lcu", "paulilcu",):
        return encode_pauli_lcu(config_general, config_unitary, hamiltonian)
    elif config_unitary.method.lower() in ("linear t", "linear-t", "lineart",):
        return encode_linear_t(config_general, config_unitary, hamiltonian)
    elif config_unitary.method.lower() in ("first quantization",):
        # TODO: This will be important for Marian's team.  Something is available in pyLIQTR, but
        #       I've not yet looked to see how it works.
        #       -- I'm not sure if it's correct to break first quantization out as a separate
        #          encoding method.  I now suspect that it will probably be part of defining the
        #          Hamiltonian, and then any Hamiltonian will be eligible for encoding to
        #          unitaries.  But I've not confirmed this.
        raise NotImplementedError()
    elif config_unitary.method.lower() in ("ramped trotter"):
        return encode_ramped_trotter(config_general, config_unitary, hamiltonian, tevol_hbar)
    else:
        raise ValueError(f"Invalid unitary encoding method \"{config_unitary.method}\".")
