#!/usr/bin/env python3
"""Visualize and rank the QHAT L-sweep Trotter benchmark results.

The script reads one or more benchmark CSV files generated by
``benchmark_L_sweep_trotter.py`` and produces:

1. Case-study grids: state error versus Trotter steps for one case,
   faceted by formula order and evolution time.
2. Family plots: one molecule/active-space family, faceted by basis,
   with bond length and ordering shown separately.
3. A robust ranking CSV comparing fermionic coloring with direct JW coloring
   and raw JW order while excluding values at the numerical floor.
4. A win-rate summary by qubit count, formula order, and evolution time.
5. A graph-complexity scatter comparing fermionic/JW graph reduction with
   fermionic/JW state-error ratio.

Examples
--------
python analysis/visualize_L_sweep_trotter.py \
    --csv analysis/l_sweep_trotter_state_t1.csv \
          analysis/l_sweep_trotter_state_t2.csv \
          analysis/l_sweep_trotter_state_t5.csv \
    --case-id He-H_0.62_hgbs-5_as-003-003 \
    --case-id Li-H_2.31_hgbs-5_as-004-004 \
    --family B-B \
    --active-occupied 2 \
    --active-vacant 4 \
    --family-formula 2 \
    --family-time 1 \
    --metric state_infidelity \
    --output-dir analysis/l_sweep_figures
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ORDERINGS = ("jw_raw", "jw_coloring", "fermionic_coloring")
ORDERING_LABELS = {
    "jw_raw": "Raw JW",
    "jw_coloring": "Direct JW coloring",
    "fermionic_coloring": "Fermionic coloring → JW",
}
ORDERING_MARKERS = {
    "jw_raw": "o",
    "jw_coloring": "s",
    "fermionic_coloring": "^",
}
ORDERING_LINESTYLES = {
    "jw_raw": "-",
    "jw_coloring": "--",
    "fermionic_coloring": "-.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualize QHAT L-sweep Trotter benchmark CSV files."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        nargs="+",
        required=True,
        help="One or more benchmark CSV files (for example t=1, 2, and 5).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("analysis/l_sweep_figures"),
    )
    parser.add_argument(
        "--metric",
        choices=("state_infidelity", "state_vector_2norm_error"),
        default="state_infidelity",
    )
    parser.add_argument(
        "--case-id",
        action="append",
        default=[],
        help="Exact case_id to plot. Repeat for multiple cases.",
    )
    parser.add_argument(
        "--auto-cases",
        type=int,
        default=0,
        help=(
            "Also plot this many automatically selected cases: half are the "
            "strongest and half the weakest fermionic-coloring cases."
        ),
    )
    parser.add_argument(
        "--family",
        default=None,
        help="Molecule name for a family plot, for example B-B.",
    )
    parser.add_argument("--active-occupied", type=int, default=None)
    parser.add_argument("--active-vacant", type=int, default=None)
    parser.add_argument("--family-formula", type=int, choices=(1, 2, 4), default=2)
    parser.add_argument("--family-time", type=float, default=1.0)
    parser.add_argument(
        "--ranking-floor",
        type=float,
        default=None,
        help=(
            "Ignore paired errors at or below this scale when ranking. "
            "Defaults to 1e-12 for infidelity and 1e-9 for state-vector error."
        ),
    )
    parser.add_argument(
        "--plot-floor",
        type=float,
        default=None,
        help=(
            "Positive floor used only for log-scale plotting. Defaults to "
            "1e-16 for infidelity and 1e-14 for state-vector error."
        ),
    )
    parser.add_argument("--dpi", type=int, default=200)
    return parser.parse_args()


def safe_filename(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", text)


def load_results(paths: Iterable[Path]) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for path in paths:
        if not path.exists():
            raise FileNotFoundError(path)
        frame = pd.read_csv(path)
        frame["source_csv"] = str(path)
        frames.append(frame)

    data = pd.concat(frames, ignore_index=True)
    if "status" in data.columns:
        data = data[data["status"].eq("success")].copy()

    required = {
        "case_id",
        "molecule",
        "bond_length",
        "basis",
        "active_occupied",
        "active_vacant",
        "n_qubits",
        "ordering",
        "formula_order",
        "trotter_steps",
        "evolution_time",
        "state_infidelity",
        "state_vector_2norm_error",
        "graph_vertices",
        "graph_edges",
        "number_of_colors",
    }
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    numeric = [
        "bond_length",
        "active_occupied",
        "active_vacant",
        "n_qubits",
        "formula_order",
        "trotter_steps",
        "evolution_time",
        "state_infidelity",
        "state_vector_2norm_error",
        "graph_vertices",
        "graph_edges",
        "number_of_colors",
        "number_of_fermionic_terms",
        "number_of_pauli_terms",
    ]
    for column in numeric:
        if column in data.columns:
            data[column] = pd.to_numeric(data[column], errors="coerce")

    data = data[data["ordering"].isin(ORDERINGS)].copy()
    data = data.drop_duplicates(
        subset=[
            "case_id",
            "evolution_time",
            "formula_order",
            "trotter_steps",
            "ordering",
        ],
        keep="last",
    )
    return data


def error_label(metric: str) -> str:
    if metric == "state_infidelity":
        return r"State infidelity $1-|\langle\psi_{\rm exact}|\psi_{\rm Trot}\rangle|^2$"
    return r"State-vector error $\|\psi_{\rm exact}-\psi_{\rm Trot}\|_2$"


def default_floors(metric: str) -> tuple[float, float]:
    if metric == "state_infidelity":
        return 1.0e-12, 1.0e-16
    return 1.0e-9, 1.0e-14


def paired_table(data: pd.DataFrame, metric: str) -> pd.DataFrame:
    index = ["case_id", "evolution_time", "formula_order", "trotter_steps"]
    paired = data.pivot_table(
        index=index,
        columns="ordering",
        values=metric,
        aggfunc="last",
    ).reset_index()
    paired.columns.name = None
    return paired.dropna(subset=list(ORDERINGS))


def build_case_ranking(
    data: pd.DataFrame,
    metric: str,
    ranking_floor: float,
) -> pd.DataFrame:
    paired = paired_table(data, metric)
    metadata_columns = [
        "case_id",
        "molecule",
        "basis",
        "active_occupied",
        "active_vacant",
        "n_qubits",
        "number_of_fermionic_terms",
        "number_of_pauli_terms",
    ]
    metadata = data[metadata_columns].drop_duplicates("case_id")

    rows: list[dict[str, object]] = []
    for case_id, group in paired.groupby("case_id", sort=False):
        record: dict[str, object] = {"case_id": case_id}
        for competitor in ("jw_coloring", "jw_raw"):
            subset = group.copy()
            largest = subset[["fermionic_coloring", competitor]].max(axis=1)
            subset = subset[largest > ranking_floor].copy()
            subset = subset[
                (subset["fermionic_coloring"] > 0.0)
                & (subset[competitor] > 0.0)
            ]
            ratios = subset["fermionic_coloring"] / subset[competitor]
            log_ratios = np.log10(ratios.to_numpy(dtype=float))
            prefix = "vs_jw_coloring" if competitor == "jw_coloring" else "vs_jw_raw"
            record[f"{prefix}_points"] = int(len(log_ratios))
            record[f"{prefix}_geometric_median_ratio"] = (
                float(10.0 ** np.median(log_ratios)) if len(log_ratios) else np.nan
            )
            record[f"{prefix}_win_fraction"] = (
                float(np.mean(log_ratios < 0.0)) if len(log_ratios) else np.nan
            )
            record[f"{prefix}_median_log10_ratio"] = (
                float(np.median(log_ratios)) if len(log_ratios) else np.nan
            )
        rows.append(record)

    ranking = pd.DataFrame(rows).merge(metadata, on="case_id", how="left")
    ranking = ranking.sort_values(
        ["vs_jw_coloring_median_log10_ratio", "case_id"],
        na_position="last",
    )
    return ranking


def plot_case_grid(
    data: pd.DataFrame,
    case_id: str,
    metric: str,
    plot_floor: float,
    output_dir: Path,
    dpi: int,
) -> Path:
    subset = data[data["case_id"].eq(case_id)].copy()
    if subset.empty:
        raise ValueError(f"No rows found for case_id={case_id!r}.")

    formula_orders = sorted(subset["formula_order"].dropna().astype(int).unique())
    times = sorted(subset["evolution_time"].dropna().unique())
    fig, axes = plt.subplots(
        len(formula_orders),
        len(times),
        figsize=(4.8 * len(times), 3.5 * len(formula_orders)),
        squeeze=False,
        sharex=True,
        sharey=True,
    )

    cycle = plt.rcParams["axes.prop_cycle"].by_key().get("color", [])
    color_for = {
        ordering: cycle[index % len(cycle)] if cycle else None
        for index, ordering in enumerate(ORDERINGS)
    }

    for row_index, formula_order in enumerate(formula_orders):
        for column_index, evolution_time in enumerate(times):
            ax = axes[row_index, column_index]
            panel = subset[
                subset["formula_order"].eq(formula_order)
                & subset["evolution_time"].eq(evolution_time)
            ]
            for ordering in ORDERINGS:
                line = panel[panel["ordering"].eq(ordering)].sort_values(
                    "trotter_steps"
                )
                if line.empty:
                    continue
                values = np.clip(
                    line[metric].to_numpy(dtype=float),
                    plot_floor,
                    None,
                )
                ax.plot(
                    line["trotter_steps"],
                    values,
                    marker=ORDERING_MARKERS[ordering],
                    linestyle=ORDERING_LINESTYLES[ordering],
                    color=color_for[ordering],
                    label=ORDERING_LABELS[ordering],
                )
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.grid(True, which="both", alpha=0.25)
            if row_index == 0:
                ax.set_title(f"t = {evolution_time:g}")
            if column_index == 0:
                ax.set_ylabel(f"Order {formula_order}\n{error_label(metric)}")
            if row_index == len(formula_orders) - 1:
                ax.set_xlabel("Trotter steps")

    first = subset.iloc[0]
    fig.suptitle(
        f"{case_id}\n"
        f"{first['molecule']}, {first['basis']}, "
        f"active space ({int(first['active_occupied'])} occupied, "
        f"{int(first['active_vacant'])} vacant), {int(first['n_qubits'])} qubits",
        y=1.01,
    )
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.suptitle(
        fig._suptitle.get_text()
        + f"\nPlotting floor: {plot_floor:g}",
        y=0.99,
    )
    fig.tight_layout(rect=(0, 0.09, 1, 0.93))
    fig.legend(
        handles,
        labels,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.012),
        ncol=3,
        frameon=False,
    )
    path = output_dir / f"case_{safe_filename(case_id)}_{metric}.png"
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_family(
    data: pd.DataFrame,
    molecule: str,
    active_occupied: int,
    active_vacant: int,
    formula_order: int,
    evolution_time: float,
    metric: str,
    plot_floor: float,
    output_dir: Path,
    dpi: int,
) -> Path:
    subset = data[
        data["molecule"].eq(molecule)
        & data["active_occupied"].eq(active_occupied)
        & data["active_vacant"].eq(active_vacant)
        & data["formula_order"].eq(formula_order)
        & np.isclose(data["evolution_time"], evolution_time)
    ].copy()
    if subset.empty:
        raise ValueError(
            "No family rows found for "
            f"{molecule}, active space {active_occupied}+{active_vacant}, "
            f"order {formula_order}, t={evolution_time}."
        )

    bases = sorted(subset["basis"].dropna().unique())
    lengths = sorted(subset["bond_length"].dropna().unique())
    fig, axes = plt.subplots(
        1,
        len(bases),
        figsize=(6.2 * len(bases), 4.8),
        squeeze=False,
        sharey=True,
    )
    axes = axes[0]
    cycle = plt.rcParams["axes.prop_cycle"].by_key().get("color", [])
    length_color = {
        length: cycle[index % len(cycle)] if cycle else None
        for index, length in enumerate(lengths)
    }

    for ax, basis in zip(axes, bases):
        panel = subset[subset["basis"].eq(basis)]
        for length in lengths:
            for ordering in ORDERINGS:
                line = panel[
                    np.isclose(panel["bond_length"], length)
                    & panel["ordering"].eq(ordering)
                ].sort_values("trotter_steps")
                if line.empty:
                    continue
                values = np.clip(line[metric].to_numpy(float), plot_floor, None)
                ax.plot(
                    line["trotter_steps"],
                    values,
                    color=length_color[length],
                    marker=ORDERING_MARKERS[ordering],
                    linestyle=ORDERING_LINESTYLES[ordering],
                )
        ax.set_title(str(basis))
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel("Trotter steps")
        ax.grid(True, which="both", alpha=0.25)
    axes[0].set_ylabel(error_label(metric))

    length_handles = [
        plt.Line2D([], [], color=length_color[length], marker="o", label=f"L = {length:g}")
        for length in lengths
    ]
    ordering_handles = [
        plt.Line2D(
            [],
            [],
            linestyle=ORDERING_LINESTYLES[ordering],
            marker=ORDERING_MARKERS[ordering],
            label=ORDERING_LABELS[ordering],
        )
        for ordering in ORDERINGS
    ]
    fig.legend(
        handles=length_handles + ordering_handles,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.015),
        ncol=min(6, len(length_handles) + len(ordering_handles)),
        frameon=False,
    )
    fig.suptitle(
        f"{molecule}, active space ({active_occupied} occupied, "
        f"{active_vacant} vacant), {active_occupied + active_vacant} qubits\n"
        f"Suzuki order {formula_order}, t = {evolution_time:g}",
        y=1.02,
    )
    fig.suptitle(
        fig._suptitle.get_text()
        + f"\nPlotting floor: {plot_floor:g}",
        y=0.99,
    )
    fig.tight_layout(rect=(0, 0.14, 1, 0.90))
    path = output_dir / (
        f"family_{safe_filename(molecule)}_as-{active_occupied:03d}-{active_vacant:03d}"
        f"_order-{formula_order}_t-{evolution_time:g}_{metric}.png"
    )
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_ranking(
    ranking: pd.DataFrame,
    metric: str,
    output_dir: Path,
    dpi: int,
    count_each_side: int = 10,
) -> Path:
    usable = ranking.dropna(subset=["vs_jw_coloring_median_log10_ratio"]).copy()
    usable = usable[usable["vs_jw_coloring_points"] >= 3]
    best = usable.nsmallest(count_each_side, "vs_jw_coloring_median_log10_ratio")
    worst = usable.nlargest(count_each_side, "vs_jw_coloring_median_log10_ratio")
    plot_data = pd.concat([best, worst]).drop_duplicates("case_id")
    plot_data = plot_data.sort_values("vs_jw_coloring_median_log10_ratio")

    fig, ax = plt.subplots(figsize=(10, max(6, 0.36 * len(plot_data))))
    y = np.arange(len(plot_data))
    ax.barh(y, plot_data["vs_jw_coloring_median_log10_ratio"])
    ax.axvline(0.0, linewidth=1.0)
    ax.set_yticks(y, plot_data["case_id"])
    ax.set_xlabel(
        "Median log10(error ratio): fermionic coloring / direct JW coloring"
    )
    ax.set_title(
        f"Most favorable and unfavorable cases ({metric})\n"
        "Negative values favor fermionic coloring"
    )
    ax.grid(True, axis="x", alpha=0.25)
    fig.tight_layout()
    path = output_dir / f"case_ranking_{metric}.png"
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_win_rates(
    data: pd.DataFrame,
    metric: str,
    ranking_floor: float,
    output_dir: Path,
    dpi: int,
) -> Path:
    paired = paired_table(data, metric)
    metadata = data[["case_id", "n_qubits"]].drop_duplicates("case_id")
    paired = paired.merge(metadata, on="case_id", how="left")
    largest = paired[["fermionic_coloring", "jw_coloring"]].max(axis=1)
    paired = paired[largest > ranking_floor].copy()
    paired["fermionic_win"] = (
        paired["fermionic_coloring"] < paired["jw_coloring"]
    )

    times = sorted(paired["evolution_time"].unique())
    formula_orders = sorted(paired["formula_order"].astype(int).unique())
    qubits = sorted(paired["n_qubits"].dropna().astype(int).unique())

    n_columns = 2
    n_rows = math.ceil(len(qubits) / n_columns)
    fig, axes = plt.subplots(
        n_rows,
        n_columns,
        figsize=(8.6, 3.9 * n_rows),
        squeeze=False,
        sharex=True,
        sharey=True,
    )
    flat_axes = axes.ravel()
    for ax, n_qubits in zip(flat_axes, qubits):
        panel = paired[paired["n_qubits"].eq(n_qubits)]
        matrix = np.full((len(formula_orders), len(times)), np.nan)
        counts = np.zeros_like(matrix, dtype=int)
        for row_index, formula_order in enumerate(formula_orders):
            for column_index, evolution_time in enumerate(times):
                cell = panel[
                    panel["formula_order"].eq(formula_order)
                    & np.isclose(panel["evolution_time"], evolution_time)
                ]
                if not cell.empty:
                    matrix[row_index, column_index] = cell["fermionic_win"].mean()
                    counts[row_index, column_index] = len(cell)
        image = ax.imshow(matrix, vmin=0.0, vmax=1.0, aspect="auto")
        for row_index in range(len(formula_orders)):
            for column_index in range(len(times)):
                value = matrix[row_index, column_index]
                if np.isfinite(value):
                    ax.text(
                        column_index,
                        row_index,
                        f"{100 * value:.0f}%\nN={counts[row_index, column_index]}",
                        ha="center",
                        va="center",
                        fontsize=8,
                    )
        ax.set_xticks(range(len(times)), [f"t={time:g}" for time in times])
        ax.set_yticks(range(len(formula_orders)), [f"Order {o}" for o in formula_orders])
        ax.set_title(f"{n_qubits} qubits")
    for ax in flat_axes[len(qubits):]:
        ax.set_visible(False)
    fig.suptitle(
        f"Fermionic-coloring win rate by problem size ({metric})\n"
        f"Pairs with both errors ≤ {ranking_floor:g} are excluded",
        y=1.02,
    )
    fig.subplots_adjust(top=0.86, right=0.97, hspace=0.25, wspace=0.12)
    path = output_dir / f"win_rate_heatmap_{metric}.png"
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return path


def plot_complexity_vs_error(
    data: pd.DataFrame,
    metric: str,
    ranking_floor: float,
    output_dir: Path,
    dpi: int,
) -> Path:
    paired = paired_table(data, metric)
    largest = paired[["fermionic_coloring", "jw_coloring"]].max(axis=1)
    paired = paired[largest > ranking_floor].copy()
    paired = paired[
        (paired["fermionic_coloring"] > 0.0)
        & (paired["jw_coloring"] > 0.0)
    ]
    paired["log_error_ratio"] = np.log10(
        paired["fermionic_coloring"] / paired["jw_coloring"]
    )
    case_error = (
        paired.groupby(["case_id", "formula_order"], as_index=False)[
            "log_error_ratio"
        ]
        .median()
        .rename(columns={"log_error_ratio": "median_log_error_ratio"})
    )

    graph = data[data["ordering"].isin(["jw_coloring", "fermionic_coloring"])].copy()
    graph = graph.drop_duplicates(["case_id", "ordering"])
    graph_edges = graph.pivot(index="case_id", columns="ordering", values="graph_edges")
    graph_vertices = graph.pivot(
        index="case_id", columns="ordering", values="graph_vertices"
    )
    metadata = data[["case_id", "n_qubits"]].drop_duplicates("case_id")
    graph_summary = pd.DataFrame(
        {
            "case_id": graph_edges.index,
            "edge_ratio": (
                graph_edges["fermionic_coloring"] / graph_edges["jw_coloring"]
            ).to_numpy(),
            "vertex_ratio": (
                graph_vertices["fermionic_coloring"]
                / graph_vertices["jw_coloring"]
            ).to_numpy(),
        }
    ).merge(metadata, on="case_id", how="left")
    plot_data = case_error.merge(graph_summary, on="case_id", how="inner")
    plot_data = plot_data.replace([np.inf, -np.inf], np.nan).dropna()

    formula_orders = sorted(plot_data["formula_order"].astype(int).unique())
    fig, axes = plt.subplots(
        1,
        len(formula_orders),
        figsize=(5.0 * len(formula_orders), 4.4),
        squeeze=False,
        sharex=True,
        sharey=True,
    )
    for ax, formula_order in zip(axes[0], formula_orders):
        panel = plot_data[plot_data["formula_order"].eq(formula_order)]
        for n_qubits, group in panel.groupby("n_qubits"):
            ax.scatter(
                group["edge_ratio"],
                group["median_log_error_ratio"],
                label=f"{int(n_qubits)} qubits",
                alpha=0.75,
            )
        ax.axhline(0.0, linewidth=1.0)
        ax.axvline(1.0, linewidth=1.0)
        ax.set_title(f"Formula order {formula_order}")
        ax.set_xlabel("Graph edge ratio: fermionic / direct JW")
        ax.grid(True, alpha=0.25)
    axes[0, 0].set_ylabel(
        "Median log10(state-error ratio): fermionic / direct JW"
    )
    handles, labels = axes[0, 0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="lower center", ncol=len(handles), frameon=False)
    fig.suptitle(
        "Does graph reduction predict Trotter-error improvement?\n"
        "Lower-left is favorable to fermionic coloring",
        y=1.02,
    )
    fig.tight_layout(rect=(0, 0.08, 1, 0.98))
    path = output_dir / f"graph_reduction_vs_error_{metric}.png"
    fig.savefig(path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return path


def main() -> None:
    args = parse_args()
    ranking_floor_default, plot_floor_default = default_floors(args.metric)
    ranking_floor = (
        args.ranking_floor
        if args.ranking_floor is not None
        else ranking_floor_default
    )
    plot_floor = args.plot_floor if args.plot_floor is not None else plot_floor_default

    args.output_dir.mkdir(parents=True, exist_ok=True)
    data = load_results(args.csv)
    ranking = build_case_ranking(data, args.metric, ranking_floor)
    ranking_path = args.output_dir / f"case_ranking_{args.metric}.csv"
    ranking.to_csv(ranking_path, index=False)

    generated: list[Path] = [ranking_path]
    generated.append(plot_ranking(ranking, args.metric, args.output_dir, args.dpi))
    generated.append(
        plot_win_rates(
            data,
            args.metric,
            ranking_floor,
            args.output_dir,
            args.dpi,
        )
    )
    generated.append(
        plot_complexity_vs_error(
            data,
            args.metric,
            ranking_floor,
            args.output_dir,
            args.dpi,
        )
    )

    case_ids = list(dict.fromkeys(args.case_id))
    if args.auto_cases > 0:
        usable = ranking[
            ranking["vs_jw_coloring_points"].ge(3)
            & ranking["vs_jw_coloring_median_log10_ratio"].notna()
        ]
        best_count = math.ceil(args.auto_cases / 2)
        worst_count = args.auto_cases - best_count
        auto = list(usable.head(best_count)["case_id"])
        if worst_count:
            auto.extend(usable.tail(worst_count)["case_id"])
        case_ids.extend(auto)
        case_ids = list(dict.fromkeys(case_ids))

    for case_id in case_ids:
        generated.append(
            plot_case_grid(
                data,
                case_id,
                args.metric,
                plot_floor,
                args.output_dir,
                args.dpi,
            )
        )

    if args.family is not None:
        if args.active_occupied is None or args.active_vacant is None:
            raise ValueError(
                "--family requires --active-occupied and --active-vacant."
            )
        generated.append(
            plot_family(
                data,
                args.family,
                args.active_occupied,
                args.active_vacant,
                args.family_formula,
                args.family_time,
                args.metric,
                plot_floor,
                args.output_dir,
                args.dpi,
            )
        )

    print(f"Loaded {len(data):,} successful benchmark rows.")
    print(f"Found {data['case_id'].nunique()} unique cases.")
    print("Generated:")
    for path in generated:
        print(f"  {path}")


if __name__ == "__main__":
    main()
